### ISSUE TITLE
Making spec look close to @spec

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#15]
I'm starting to try this out and wondering if what I'm seeing in terms of interaction with the formatter and compiler is the same for you. I have the following spec:

```elixir
spec get_contact_request(uuid, list(function) | function) :: nil | ContactRequest.t()

def get_contact_request(id, opts \\ []) do
```

A few notes:
1. The formatter respects `spec` without parens after I added `  locals_without_parens: [type: 1, typep: 1, opaque: 1, spec: 1]` to `.formatter.exs`. Curiously, adding `:type_check` to `:import_deps` did not seem to work for me so needed to add them directly.
2. One issue I run into is that the compiler still warns that there are missing parens on `function` and `uuid` (my own type) so perhaps I'll either need to add parens or live with the compiler warnings.
3. The formatter always adds an empty line between `spec` and my function. Not sure there is any way around this, but it would feel like more of a regular `@spec` if this newline weren't necessary.
4. The formatter always adds parens for `.t` (example `ContactRequest.t()`). Not a big deal, but it seems like your examples display without parens so wondering if there is any configuration you've done to allow this.

**Comment by Qqwy** [comment]
Thank you very much for your feedback!

1. Adding `:type_check` to the `import_deps:` should work; I'll open a separate issue for this. 
2. I am unsure how to approach this. Currently the type-expander code is able to expand variables to functions (i.e. automatically add the `()` without the user needing to add them), but only if those types are defined above where they are used, which means that it unfortunately does not work everywhere.
3. This is indeed very unfortunate. I'll see if there is a formatter-setting that TypeCheck can use to make it _not_ do that, but I am not sure if it is at all possible.
4. I have not run the formatter on all the examples. One thing you might do of course is to add `t: 0` to `locals_without_parens`.

**Comment by baldwindavid** [comment]
2. Hm. I am importing the `uuid` type at the top of the file in this example:

```elixir
spec get_account(uuid, query_opts()) :: Account.t() | nil
```

However, I still receive the following error: 

```
warning: variable "uuid" does not exist and is being expanded to "uuid()", please use parentheses to remove the ambiguity or change the variable name
  lib/type_check/macros.ex:32: Elevate.AccountMgmt.Accounts."__type_check_spec_for_get_account/2__"/0
```

Is this a case where you think that it should already be working?

---

4. Yeah, I had tried to add `t: 0` to `locals_without_parens`. It works for schemas, but the majority of usage is for cases where it is remote (ex. `Account.t`) so makes sense that it wouldn't work there.

---

None of these 4 items I mentioned would stop me from using the package. Thanks!

**Comment by Qqwy** [comment]
Closing this one since the different parts are handled in separate issues :slightly_smiling_face: .
