### ISSUE TITLE
Can not define type in a non-Elixir module

### ISSUE THREAD

**Issue by xhh** [Qqwy/elixir-type_check#174]
When defining type in a non-Elixir module:

```elixir
defmodule :my_mod do
  use TypeCheck

  @type! str :: String.t()

  @spec! hello(str()) :: :ok
  def hello(name) do
    IO.puts("Hello #{name}!")
    :ok
  end
end
```

an compilation error occurs:

```
** (ArgumentError) expected an Elixir module, got: :my_mod
    (elixir 1.14.3) lib/module.ex:1677: Module.split/2
    (type_check 0.13.2) lib/type_check/macros.ex:626: TypeCheck.Macros.type_fun_definition/5
    (type_check 0.13.2) lib/type_check/macros.ex:536: TypeCheck.Macros.define_type/3
    lib/my_mod.ex:4: (module)
```

**Comment by xhh** [comment]
It could be fixed by checking if the module is an Elixir module like [this in the elixir_sense project](https://github.com/elixir-lsp/elixir_sense/blob/6d1a951bfbfc02e93b410acded82c736e1806df2/lib/elixir_sense/core/introspection.ex#L1115) before calling `Module.split`.

**Comment by Qqwy** [comment]
Thank you very much! This indeed seems like a bug. I'll try to fix it shortly.

**Comment by Qqwy** [comment]
Version 0.13.3 has been published, which includes a fix for this bug.
