### ISSUE TITLE
Should keyword list be builtin?

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#18]
I attempted to use `keyword()` in a spec and got a compilation error of `undefined function keyword/0` as I thought it might be built in. I then tried to create a custom type of the same name and got the compilation error of `type keyword/0 is a built-in type and it cannot be redefined`. I am a little confused by these compilation errors.

I ended up making adding a type of a slightly different name:

```elixir
type keyword_list :: list({atom(), any()})
```

That works fine, but wasn't sure if this was expected behavior.

**Comment by Qqwy** [comment]
Correct, `keyword` is one of the few Elixir built-in types that currently is not built-in into TypeCheck. It should definitely be added before a stable release.

**Comment by Qqwy** [comment]
Release 0.1.2 contains the new `keyword()` and `keyword(t)` types.
