### ISSUE TITLE
Possibility of making structs type-safe?

### ISSUE THREAD

**Issue by Qqwy** [Qqwy/elixir-type_check#21]
`defstruct` is in the end syntactic sugar around a definition of `__struct__/0` (which creates an empty 'default' version of the struct map) and `__struct__/1` (which merges the given enumerable into an existing struct. It is for instance called when someone calls `%Foo{struct | a: 1, b: 2}`).

This means that we could override it with a version that checks a struct's keys against their types every time someone uses `%Foo{}` or `%Foo{foo | some: value}`.

The best way to do this is probably _not_ to override `defstruct` itself (because this, for instance, would make it impossible to use TypeCheck together with other libraries that customize or wrap `defstruct` like for instance Ecto) but to provide a separate compile-time macro `type_check_struct/1` that accepts a type as (the single) parameter, which will use `defoverridable` to override `__struct__/{0,1}` with versions that perform type-checking before calling `super`.

---

This is a cool but advanced feature that is not planned to be added for some time (unless someone else wants to write a PR), but it's something I stumbled upon while thinking about other things, so I thought I would write it down to not forget.

**Comment by Qqwy** [comment]
I came across a very interesting section of the [Erlang documentation](http://erlang.org/doc/reference_manual/typespec.html#type-information-in-record-declarations). Turns out that in Erlang, there is a built-in syntax to add types to record declarations.

We could do something similar for structs. I'm thinking about a syntax like:

```elixir
defmodule User do
  defstruct!(
    :email   :: Email.t(), # This is a required field and thus does not have a default value; we can automatically add it to `@enforced_keys` as well.
    name: "" :: binary(),
    age: 0   :: integer(),
  )
end
```

**Comment by baldwindavid** [comment]
This seems like a neat feature. At the same time I get this nagging feeling that generating a struct is kind of out of scope for a type checking package. Does this seem right in scope to you?

**Comment by tcoopman** [comment]
I'm not sure about that. Aren't structs basically typed maps, and thus something that would be in scope?

On the other hand it does feels bit at the edge of the scope. The use of a custom `@spec!` (Vs `@spec`) makes interop with for example `typedstruct` hard though, so that is an other reason why this project could add it?

**Comment by baldwindavid** [comment]
@Qqwy Do you think this sort of thing would be better within this Typecheck or to integrate with a package such as Domo? https://github.com/IvanRublev/Domo

**Comment by Qqwy** [comment]
@baldwindavid I definitely think that a feature like this would be a good addition to either Typecheck or maybe a separate library that strongly leans on Typecheck (e.g. a `typecheck-structs` or something).

What `Domo` does is nice, but the kind of functionality that is shown in `Domo`'s readme is already possible with Typecheck today:

```elixir
defmodule LineItem do
  use TypeCheck
  defstruct amount: 0
  @type! t :: %__MODULE__{
    amount: non_neg_integer()
  }
end

defmodule PurchaseOrder do
  use TypeCheck

  defstruct id: 1000, approved_limit: 200, items: []
  @type! id :: non_neg_integer() when 1000 <= id and id <= 5000


  @type! t :: %__MODULE__{
    id: id(),
    approved_limit: pos_integer(),
    items: list(LineItem.t())
  } when validate_invariants(t)

  defp validate_invariants(po) do
    amounts =
      po.items
      |> Enum.map(& &1.amount)
      |> Enum.sum()

    amounts <= po.approved_limit
  end

  @spec! new(%{approved_limit: pos_integer(), id: id(), items: list(LineItem.t())}) :: t()
  def new(args) do
    struct(__MODULE__, args)
  end
end

```

**Comment by baldwindavid** [comment]
@Qqwy Whoops, I linked that off of the library I actually meant, which was TypedStruct... https://github.com/ejpcmac/typed_struct

Probably I'm most interested in it as a way to eliminate https://github.com/Qqwy/elixir-type_check/issues/83 and to enforce consistency of defining structs across a codebase.
