### ISSUE TITLE
Dynamic @spec! via defmacro

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#36]
I am attempting to write a macro that dynamically writes a function. Additionally, I would like the corresponding `@spec!` to be written above it. This is referenced in a [thread in ElixirForum](https://elixirforum.com/t/typecheck-fast-and-flexible-runtime-type-checking-for-your-elixir-projects/32886/60?u=baldwindavid) where you mention posting as an issue here.

This is a stripped down example where I have a macro that is dynamically named. The macro (with `@spec!` commented out) is the following:

```elixir
defmodule MacroSpec do
  defmacro my_macro(name) do
    quote bind_quoted: [name: name] do
      # @spec! unquote(:"my_function_#{name}")(binary) :: binary
      def unquote(:"my_#{name}")(greeting) do
        IO.inspect(unquote(name))
        IO.inspect(greeting)
        greeting
      end
    end
  end
end
```

This module is then imported to MyModule and `my_macro` is called.

```elixir
defmodule MyModule do
  import MacroSpec

  MacroSpec.my_macro("greeter")
end
```

The `my_greeter` function can then be called with a string.

```elixir
MyModule.my_greeter("hello world!")
```

This all works fine, but breaks down when I uncomment the `@spec!`. The syntax that is there right now clearly won't work at all because it is trying to evaluate that line and trips over the `::`, but I am posting this way to give you the best idea of what it is trying to achieve. I can `use TypeCheck`, but I don't believe I want it even caring about TypeCheck during compilation of the macro.

I've tried various things like using Macro.escape and quoting the entire line. I'm pretty sure this just comes down to me not understanding how to quote/unquote/escape the right parts of the spec rather than anything specific to TypeCheck, but posting here in case there is something unique.

**Comment by Qqwy** [comment]
I see. It might be the case that the hygienic nature that `quote` (by default at least) has is creating an inconvenience here: it might not recognize `@spec!` (or to be precise, the macro TypeCheck.@/1) which is necessary to parse `::` as TypeCheck would rather than Elixir's builtin way (which will crash anywhere where we're not building either a type-specification or a binary pattern match).

I'll try some related variants of this and get back to you with my findings.

**Comment by Qqwy** [comment]
I've encountered the following problems:

1. Indeed Elixir complains about `::`. Even when adding `use TypeCheck` inside of the `quote` this problem remains. Seemingly overriding `@` inside of the quote does not have the desired effect. This can be circumvented by directly using `spec!`. Not perfect (I hope to find out how to make `@` work inside a quote) but O.K. for now, I think.
2. we have the dilemma of working with a quote that contains a `def`, which introduces its own nested context (c.f. 'binding and unquote fragments' in the [quote documentation](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#quote/2-binding-and-unquote-fragments)). `spec!` requires a normal `unquote`. However, customizing the name given to `def` requires an unquote fragment. There is no easy way to mix-and-match these styles.

I'll see if there is a way to let `spec!` work well with `unquote` fragments, or if there is another way to resolve this dilemma.

**Comment by Qqwy** [comment]
Supporting unquote fragments inside  `@type!` and `@spec!` definitely seems the way to go because [Elixir itself supports this for @type](https://github.com/elixir-lang/elixir/blob/82dca5537a4956b33367cf05d694894055c7ce80/lib/elixir/test/elixir/typespec_test.exs#L760)

**Comment by Qqwy** [comment]
For myself and posterity: https://github.com/elixir-lang/elixir/commit/ffb2258bb16c822595faf3d69e8d41c12ef2d5e3 is how this was implemented in Elixir itself.

**Comment by baldwindavid** [comment]
Thank you for taking a look. If I'm understanding correctly when you say `spec!` works I assumed you were saying by doing the following:

```elixir
defmodule MacroSpec do
  defmacro my_macro(name) do
    [
      quote do
        spec!(unquote(:"my_#{name}")(binary) :: any)
      end,
      quote bind_quoted: [name: name] do
        def unquote(:"my_#{name}")(greeting) do
          IO.inspect(unquote(name))
          IO.inspect(greeting)
          greeting
        end
      end
    ]
  end
end
```

This does work in my example case, though I'm having trouble when trying to reference an argument passed to the macro that is a map. I'll checkout your PR.

**Comment by Qqwy** [comment]
When the PR is merged, you can do the following:

```elixir
      defmodule MacroSpec do
        defmacro my_macro(name) do
          quote bind_quoted: [name: name], location: :keep do
            use TypeCheck

            spec! unquote(:"my_function_#{name}")(binary) :: binary
            def unquote(:"my_function_#{name}")(greeting) do
              greeting
            end
          end
        end
      end
```

**Comment by baldwindavid** [comment]
Yep, works spectacularly. Thanks!
