### ISSUE TITLE
Using @spec! allows calling private functions

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#64]
I was surprised to find that adding `@spec!` to a private function exposes that function publicly.

```elixir
defmodule Typetest do
  use TypeCheck

  @spec! hello :: any()
  defp hello, do: "world"
end

# This works...
Typetest.hello()
```

I noticed it when changing a public function to private and seeing that my test of the function still somehow worked.

**Comment by Qqwy** [comment]
Interesting. 
This is definitely not intended behaviour.

I will ask about this upstream, because it feels to me like this (using a spec on a private function) should result in a compiler error by Elixir itself.

**Comment by Qqwy** [comment]
It turns out that Elixir itself does allow this.
So we'll need to add a check ourselves, to make sure that we keep a `defp`-function `defp`.

**Comment by baldwindavid** [comment]
I saw your documentation change in core. That is good information to know!

**Comment by baldwindavid** [comment]
I don't think it's too common to add them to private functions, but I wouldn't expect a compile-time error when doing so. I haven't done it, but I've at least heard some of our devs lament that it might be easier to follow some of our complex flows if there were specs even on some private functions.

Perhaps some validation that specs on private functions should be allowed in TypeCheck?... https://github.com/elixir-lang/elixir/issues/3144#issuecomment-77678584
