### ISSUE TITLE
Handle %{optional(type) => other_type} and other embellished map-syntaxes

### ISSUE THREAD

**Issue by Qqwy** [Qqwy/elixir-type_check#7]
These are currently not supported by TypeCheck. There's no technical reason why they are not supported, other than that it requires some effort to make the syntax work.

Implementing this requires to extend the `Map` and/or `FixedMap` structs.

**Comment by Qqwy** [comment]
This is quite tricky. Current idea I have:

1. The exact size of the map is only checked if there is no `optional(key_type) => value_type`. (If it exists, we can still check for a 'minimum size' as optimization).
1. For all key-value pairs of the shape `required(literal(key_val)) => value_type`, we can use the check we use currently, where we check `rest = Map.keys(map) -- required_keys`. If there are only literal keys, rest should equal `[]`. If not, we continue with `rest`:
2. For all other key-value pairs of the shape `required(key_type) => `value_type` we need to look at them one-by-one:
  - For each of them, we have to keep track of _all_ `key_type`s that a particular key matches.
  - When having gathered all of them, combine them into a `MapSet`. This should be the same as the set of all key types.
  Why do we need to track all of them? Because we might have a type like `%{required(integer()) => any(), required(1..256) => any())`. If the actual map has the shape `%{2 => :ok, 300 => :ok}` then we need to make sure that the `2` is used for the second type, rather than preventing the `300` to match with the first.
3. For each key which does not match any of the required types, we attempt to match it with _any_ of the optional types. If none is found, then we report this as error.

**Comment by Qqwy** [comment]
As written in the [Elixirforum topic](https://elixirforum.com/t/typecheck-fast-and-flexible-runtime-type-checking-for-your-elixir-projects/32886/89?u=qqwy)

<blockquote>
I've been thinking more about this.

Trying to support everything at once probably is a fool's errand, for two reasons:
1. It is very difficult to build this full implementation
2. The resulting runtime checks will by necessity be very slow.

Instead, I think a better approach might be to add support for some common subpatterns (but not yet all of them).

Essentially:
- `%{optional(k) => v}`: Could be supported right now as it is identical to TypeCheck's nonstandard `map(k, v)`.
- `%{required(k) => v}`: Could be supported right now as it is identical to TypeCheck's nonstandard `m :: map(k, v) when map_size(m) >= 1`.
- `%{a: x, b: y, ..., optional(k) => v}`: Could be supported by:
  - Using the existing checks on all literal key-values
  - For all (if any) leftover key-values, check whether they match `k => v`.
- The approach in the previous bullet can also be used for any number of `required(  )` followed by a single `optional(  )` as long as all `required` types are literal types.

We then explicitly do **not** (for now) support having multiple non-literal `required(  )` and/or multiple `optional(  )` in a single type. I think is OK because (a) such types are to my knowledge very rare and (b) again it is super difficult to implement checks for potentially-overlapping types efficiently; currently I know no better approach to match these than to check whether at least one solution exists in the cartesian product of (`keys × powerset(required_keytypes)`).
</blockquote>

**Comment by Qqwy** [comment]
What was mentioned in above post has now been implemented.

I'll close this issue for now. If in the future you have a need for more complicated map syntaxes, feel free to create a new issue for it describing your situation. :slightly_smiling_face:

**Comment by dvic** [comment]
@Qqwy there is one usecase that is common and might be easy to implement: 

```elixir
%{
  some_required_key: integer(),
  optional(:optional_key1) => float(),
  optional(:optional_key2) => String.t()
}
```

The idea I had is to represent the optional keys in this specific case as a `Builtin.FixedMap` instead of `Builtin.Map` but with an additional support for optional keys. The reasoning here is that in the above example the "optional" set is basically the same as the structure for `Builtin.FixedMap` but then with the exception that all keys are optional in term of their presence.

**Comment by dvic** [comment]
Just to clarify here: I would like to implement support for multiple optionals if the type of each optional is a literal atom

**Comment by dvic** [comment]
Update: submitted #165 which adds support for maps like 

```elixir
%{
  some_required_key: integer(),
  optional(:optional_key1) => float(),
  optional(:optional_key2) => String.t()
}
```
