### ISSUE TITLE
External types

### ISSUE THREAD

**Issue by marcandre** [Qqwy/elixir-type_check#86]
Interesting and promising library.

I imagine there's a way to deal with types defined in dependencies?

```
** (UndefinedFunctionError) function Plug.Conn.t/0 is undefined or private
```

Is there a package for popular packages, e.g. `phoenix`?

**Comment by baldwindavid** [comment]
I'm unaware of any packages for popular packages, but perhaps [this answer](https://elixirforum.com/t/typecheck-fast-and-flexible-runtime-type-checking-for-your-elixir-projects/32886/84) helps.

This link appears in that answer, but here is the documentation for [Remote Type Overrides](https://hexdocs.pm/type_check/comparing-typecheck-and-elixir-typespecs.html#remote-type-overrides).

**Comment by Qqwy** [comment]
Libraries containing type definitions for popular libraries like Phoenix, Ecto, Jason, Decimal, Plug, etc. are planned, but have a lower priority than finishing the core library itself. Help with this would be great!

For now, you can add remote type overrides manually, as shown in @baldwindavid's reply.
